eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8010/eureka/

words: boat,book,vote,seat,backpack,partition,groundhog

# Assigns a random, unused port
server:
  port: ${PORT:${SERVER_PORT:0}}