eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8010/eureka/

words: reasonable,leaky,suspicious,ordinary,unlikely

# Assigns a random, unused port
server:
  port: ${PORT:${SERVER_PORT:0}}